{% set name = "openquake.engine" %}
{% set version = "3.10.1" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 669dd5ef1a451d3511436c43d40fa4cea98862917ebd8922d8deadafc41b738a

build:
  number: 2
  entry_points:
    - oq = openquake.commands.__main__:oq
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - decorator >=4.3
    - django >=1.11,
    - docutils >=0.11,
    - h5py >=2.9,
    - matplotlib >=1.5,
    - numpy >=1.16,
    - pandas >=0.25,
    - pip
    - psutil >=2.0,
    - pyshp ==1.2.3
    - python >=3.6
    - pyzmq <20.0
    - requests >=2.20,
    - scipy >=1.3,
    - setuptools
    - shapely >=1.3,
    - toml
  run:
    - decorator >=4.3
    - django >=1.11,
    - docutils >=0.11,
    - h5py >=2.9,
    - matplotlib >=1.5,
    - numpy >=1.16,
    - pandas >=0.25,
    - psutil >=2.0,
    - pyshp ==1.2.3
    - python
    - pyzmq <20.0
    - requests >=2.20,
    - scipy >=1.3,
    - setuptools
    - shapely >=1.3,
    - toml

test:
  imports:
    - openquake

about:
  home: https://github.com/gem/oq-engine
  license: AGPL-3.0-only
  summary: Computes earthquake hazard and risk.
  license_family: AGPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
