{% set name = "openquake.engine" %}
{% set version = "3.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openquake.engine-{{ version }}.tar.gz
  sha256: 8fd4eacefffc04cd91f41a8bed1fb71b882f0f447b419c27bfcbc91b8ab0a25d

build:
  number: 0
  noarch: python
  entry_points:
    - oq = openquake.commands.__main__:oq
  script:
    # conda package handling is not happy with special characters in this
    # example on Windows.
    - rm -rf openquake/qa_tests_data/classical_risk/case_5
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - alpha-shapes >=1.1.0
    - python >=3.8
    - setuptools
    - h5py >=2.10
    - numpy >=1.20
    - scipy >=1.3
    - pandas >=0.25
    - pyzmq >=19.0
    - psutil >=2.0
    - shapely >=1.7
    - docutils >=0.11
    - decorator >=4.3
    - django >=4.2,<5
    - matplotlib-base
    - requests >=2.20
    - toml >=0.10.2
    - pyproj >=1.9
    - numba >=0.56
    # not listed in the metadata but required
    - fiona
    - networkx

test:
  imports:
    - openquake
    - openquake.baselib
  requires:
    - pip
  commands:
    - pip check
    - oq --version

about:
  home: https://github.com/gem/oq-engine
  license: AGPL-3.0-only
  summary: Computes earthquake hazard and risk.
  license_family: AGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
