{% set name = "openquake.engine" %}
{% set version = "3.16.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openquake.engine-{{ version }}.tar.gz
  sha256: d052a086ab0fb47bc766f5dda2d40eefe3aea19420117f68aa852e6a1447d260

build:
  number: 0
  noarch: python
  entry_points:
    - oq = openquake.commands.__main__:oq
  script:
    # conda package handling is not happy with special characters in this
    # example on Windows.
    - rm -rf openquake/qa_tests_data/classical_risk/case_5
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - decorator >=4.3
    - django >=3.2
    - docutils >=0.11
    - gdal >=3.6
    - h5py >=3.5
    - matplotlib-base >=3.0
    - numpy >=1.22
    - pandas >=2.0
    - psutil >=2.0
    - pyproj >=1.9
    - pyzmq >=19.0
    - requests >=2.20
    - scipy >=1.8
    - setuptools
    - shapely >=2.0
    - toml >=0.10.2

test:
  imports:
    - openquake
    - openquake.baselib
  requires:
    - pip
  commands:
    - pip check
    - oq --version

about:
  home: https://github.com/gem/oq-engine
  license: AGPL-3.0-only
  summary: Computes earthquake hazard and risk.
  license_family: AGPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
