{% set name = "openquake.engine" %}
{% set version = "3.21.0" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openquake_engine-{{ version }}.tar.gz
  sha256: bcf433f6a44c98b9c9118c6e0571ac8e8fc10230e36adcab1ecb55453090f2f8

build:
  number: 0
  noarch: python
  entry_points:
    - oq = openquake.commands.__main__:oq
  script:
    # conda package handling is not happy with special characters in this
    # example on Windows.
    - rm -rf openquake/qa_tests_data/classical_risk/case_5
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=69.0
    - pip
  run:
    - python >={{ python_min }}
    - alpha-shapes >=1.1.0
    - setuptools >=69.0
    - h5py >=3.10
    - numpy >=1.26,<2
    - scipy >=1.11.4
    - pandas >=2,<2.1
    - pyzmq >=26.0
    - psutil >=2.0
    - shapely >=1.7
    - docutils >=0.11
    - decorator >=4.3
    - django >=4.2,<5
    - matplotlib-base
    - requests >=2.20
    - toml >=0.10.2
    - pyproj >=3.6.1
    - numba >=0.58
    # not listed in the metadata but required
    - h3 >=3.7.7
    - fiona >=1.9.5
    - networkx
    - gdal >=3.7.3

test:
  imports:
    - openquake
    - openquake.baselib
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - oq --version

about:
  home: https://github.com/gem/oq-engine
  license: AGPL-3.0-only
  summary: Computes earthquake hazard and risk.
  license_family: AGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
