{% set name = "openquake.engine" %}
{% set version = "3.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openquake.engine-{{ version }}.tar.gz
  sha256: 275adc9ada20f98d353a2bcbef446201274dcea85192b4b2423f60249ce626b1

build:
  number: 0
  noarch: python
  entry_points:
    - oq = openquake.commands.__main__:oq
  script:
    # conda package handling is not happy with special characters in this
    # example on Windows.
    - rm -rf openquake/qa_tests_data/classical_risk/case_5
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - decorator >=4.3
    - django >=1.11,<2.3
    # - django >=1.11
    # This pin is too tight and we cannot resolve for it.
    # - docutils >=0.11,<0.15
    - docutils >=0.11
    - gdal
    - h5py >=2.9,<2.11
    - matplotlib-base >=1.5,<3.2
    # This pin is too tight and we cannot resolve for it.
    # - numpy >=1.16,<1.19
    - numpy >=1.16
    - pandas >=0.25,<1.1
    - psutil >=2.0,<5.7
    - pyproj
    # This pin is too tight and we cannot resolve for it.
    # - pyshp ==1.2.3
    - pyshp
    - pyzmq <20.0
    - requests >=2.20,<2.24
    # This pin is too tight and we cannot resolve for it.
    - scipy >=1.3
    - setuptools
    - shapely >=1.3,<1.8
    - toml

test:
  imports:
    - openquake
    - openquake.baselib
  requires:
    - pip
  commands:
    # we cannot run pip check b/c of the pins we are not breaking above
    # - pip check
    - oq --version

about:
  home: https://github.com/gem/oq-engine
  license: AGPL-3.0-only
  summary: Computes earthquake hazard and risk.
  license_family: AGPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
