schema_version: 1

context:
  python_min: "3.11"
  version: "3.26.2"

package:
  name: openquake.engine
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/openquake.engine/openquake_engine-${{ version }}.tar.gz
  sha256: 82644c4279735d38e83d764114a56e5992127b541b032d4eda859bc3e8717a26

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - oq = openquake.commands.__main__:oq

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=79.0
    - pip
  run:
    - python >=${{ python_min }}
    - alpha-shapes >=1.1.0
    - decorator >=5.1.1
    - django >=4.2,<5
    - django-cors-headers >=4.3.1
    - docutils
    - fiona >= 1.10.1
    - gdal >= 3.13.1
    - geopandas >=1.1.4
    - h3-py >=4.4
    - h5py >=3.13
    - matplotlib-base
    - numba >=0.61.2,<0.62.dev0
    - numpy >=2,
    - pandas >=2,<2.2.3
    - pillow >=12
    - psutil
    - pyproj >=3.7.2
    - pyogrio >=0.12.1
    - pyzmq >=26
    - requests
    - scipy
    - shapely
    - toml >=0.10.2

tests:
  - python:
      imports:
        - openquake._unc
        - openquake._unc.processing
      # This library is pinned too tight upstream as if it was an app.
      # As far as I could test there is no reason for that and everything works.
      # While pip-check false is bad, this package is "end-of-stack" and it is
      # unlikely to break anything downstream.
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - '*'
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - oq --help

about:
  summary: Computes earthquake hazard and risk.
  license: AGPL-3.0-only
  license_file:
    - LICENSE
  homepage: https://github.com/gem/oq-engine

extra:
  recipe-maintainers:
    - cbworden
    - emthompson-usgs
    - mhearne-usgs
    - ocefpaf
